### ISSUE TITLE
Does not work with chatId = 0

### ISSUE THREAD

**Issue by jasperkuperus** [jehy/telegram-test#2]
If you do `sendUpdate(0, '/start hola');`, internally `chatId = 1` will be used and the setup won't work. I think this happens on line 35:

```
options.chatId = options.chatId || 1;
```

**Comment by jehy** [comment]
Do you really need to use zero as chatId? I don't think that it is correct...

**Comment by jasperkuperus** [comment]
I don't really need it, but the example had the following line which made me believe it was possible:

```
let testChat = 0;
```

I see now that you increment it before using it. Did not see that before.

**Comment by jehy** [comment]
Yup, that's pretty confusing. Updated readme and added check for chatId (version 0.1.3). Thanks!
